[ 'Oscar Bluth', 
  'Barry Zuckerkorn',
  'Maggie Lizer',
  'Lucille Austero',
  'Steve Holt',
  'Carl Weathers',
  'Marta Estrella',
  'Rita Leeds',
  'Kitty Sanchez',
  'Stan Sitwell',
  'Sally Sitwell',
  'Moses Taylor',
  'Tony Wonder',
  'Cindi Lightballoon' ]
