development:
  adapter: postgresql
  encoding: unicode
  database: mutual_aid_dev
  pool: 5
  username: jeremyweiland
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: mutual_aid_test
  pool: 5
  username: jeremyweiland
  password: 

